#!/bin/bash
#===============================================================================
# Ubuntu Headless + SSH Full Control + LAN/WiFi Auto-Failover
# Auto-detect hardware & adapt configuration
#===============================================================================

set -e

#-------------------------------------------------------------------------------
# KONFIGURASI USER (Edit sesuai kebutuhan)
#-------------------------------------------------------------------------------
WIFI_SSID="${WIFI_SSID:-}"
WIFI_PASS="${WIFI_PASS:-}"
SSH_PORT=22
ALLOWED_USER="${SUDO_USER:-$USER}"
STATIC_IP=""        # Kosongkan untuk DHCP, isi untuk static (e.g., "192.168.1.100/24")
GATEWAY_IP=""       # Untuk static IP (e.g., "192.168.1.1")
DNS_IPS=""          # Untuk static IP (e.g., "8.8.8.8,1.1.1.1")

#-------------------------------------------------------------------------------
# FUNGSI DETEKSI HARDWARE
#-------------------------------------------------------------------------------
detect_hardware() {
    echo "[*] Mendeteksi hardware..."
    
    # Deteksi interface jaringan
    ETH_IFACE=$(ip link show | grep -E "^[0-9]+: e" | awk -F: '{print $2}' | tr -d ' ' | head -1)
    WIFI_IFACE=$(ip link show | grep -E "^[0-9]+: w" | awk -F: '{print $2}' | tr -d ' ' | head -1)
    
    # Jika tidak ditemukan, coba dengan pola lain
    [[ -z "$ETH_IFACE" ]] && ETH_IFACE=$(ls /sys/class/net/ | grep -E "eth|enp|eno|ens" | head -1)
    [[ -z "$WIFI_IFACE" ]] && WIFI_IFACE=$(ls /sys/class/net/ | grep -E "wlan|wlp|wlo" | head -1)
    
    # Deteksi Display Manager
    if systemctl list-unit-files | grep -q "gdm.service"; then
        DISPLAY_MGR="gdm"
    elif systemctl list-unit-files | grep -q "sddm.service"; then
        DISPLAY_MGR="sddm"
    elif systemctl list-unit-files | grep -q "lightdm.service"; then
        DISPLAY_MGR="lightdm"
    else
        DISPLAY_MGR="none"
    fi
    
    # Deteksi renderer Netplan
    if systemctl is-active --quiet NetworkManager; then
        NET_RENDERER="NetworkManager"
    else
        NET_RENDERER="networkd"
    fi
    
    # Deteksi arsitektur & Ubuntu version
    UBUNTU_VER=$(lsb_release -rs)
    ARCH=$(dpkg --print-architecture)
    
    echo "    ✓ Ethernet: ${ETH_IFACE:-TIDAK DITEMUKAN}"
    echo "    ✓ WiFi: ${WIFI_IFACE:-TIDAK DITEMUKAN}"
    echo "    ✓ Display Manager: $DISPLAY_MGR"
    echo "    ✓ Network Renderer: $NET_RENDERER"
    echo "    ✓ Ubuntu: $UBUNTU_VER ($ARCH)"
}

#-------------------------------------------------------------------------------
# FUNGSI INSTALL PACKAGE
#-------------------------------------------------------------------------------
install_packages() {
    echo "[*] Menginstall package yang diperlukan..."
    apt-get update
    
    PACKAGES="openssh-server net-tools wireless-tools wpasupplicant"
    
    # Tambahkan package sesuai versi
    if [[ "$UBUNTU_VER" < "22.04" ]]; then
        PACKAGES="$PACKAGES ifupdown"
    fi
    
    # Untuk bonding
    if [[ -n "$ETH_IFACE" && -n "$WIFI_IFACE" ]]; then
        PACKAGES="$PACKAGES ifenslave"
    fi
    
    apt-get install -y $PACKAGES
}

#-------------------------------------------------------------------------------
# FUNGSI KONFIGURASI HEADLESS
#-------------------------------------------------------------------------------
setup_headless() {
    echo "[*] Mengkonfigurasi mode headless..."
    
    # Set boot target ke multi-user (non-GUI)
    systemctl set-default multi-user.target
    
    # Disable Display Manager
    if [[ "$DISPLAY_MGR" != "none" ]]; then
        systemctl disable "$DISPLAY_MGR" 2>/dev/null || true
        echo "    ✓ $DISPLAY_MGR dinonaktifkan"
    fi
    
    # Disable layanan grafis yang tidak perlu
    systemctl disable bluetooth 2>/dev/null || true
    systemctl disable cups 2>/dev/null || true
    systemctl disable cups-browsed 2>/dev/null || true
    
    echo "    ✓ Boot target: multi-user.target"
}

#-------------------------------------------------------------------------------
# FUNGSI KONFIGURASI SSH
#-------------------------------------------------------------------------------
setup_ssh() {
    echo "[*] Mengkonfigurasi SSH..."
    
    # Backup konfigurasi original
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)
    
    # Generate SSH config baru
    cat > /etc/ssh/sshd_config <<EOF
# Auto-generated by headless setup script
Port $SSH_PORT
ListenAddress 0.0.0.0

# Authentication
PubkeyAuthentication yes
PasswordAuthentication yes
PermitRootLogin no
MaxAuthTries 3
MaxSessions 10

# X11 Forwarding untuk GUI via SSH
X11Forwarding yes
X11DisplayOffset 10
X11UseLocalhost no

# Keep connection alive
ClientAliveInterval 60
ClientAliveCountMax 3
TCPKeepAlive yes

# Security hardening
Protocol 2
LoginGraceTime 120
UsePAM yes
AllowUsers $ALLOWED_USER

# Logging
SyslogFacility AUTH
LogLevel INFO

# Subsystem
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

    # Enable & restart SSH
    systemctl enable ssh
    systemctl restart ssh
    
    echo "    ✓ SSH aktif di port $SSH_PORT"
    echo "    ✓ User diizinkan: $ALLOWED_USER"
}

#-------------------------------------------------------------------------------
# FUNGSI KONFIGURASI FAILOVER LAN/WiFi
#-------------------------------------------------------------------------------
setup_failover() {
    echo "[*] Mengkonfigurasi failover jaringan..."
    
    # Backup Netplan config
    NETPLAN_DIR="/etc/netplan"
    mkdir -p "$NETPLAN_DIR"
    mv "$NETPLAN_DIR"/*.yaml "$NETPLAN_DIR"/backup/ 2>/dev/null || true
    mkdir -p "$NETPLAN_DIR"/backup
    
    # Generate Netplan config berdasarkan hardware yang terdeteksi
    if [[ -n "$ETH_IFACE" && -n "$WIFI_IFACE" ]]; then
        # Mode: Bonding LAN + WiFi
        setup_bonding
    elif [[ -n "$ETH_IFACE" ]]; then
        # Hanya LAN
        setup_ethernet_only
    elif [[ -n "$WIFI_IFACE" ]]; then
        # Hanya WiFi
        setup_wifi_only
    else
        echo "    ⚠ Tidak ada interface jaringan terdeteksi!"
        exit 1
    fi
}

setup_bonding() {
    echo "    → Mode: LAN + WiFi Bonding (Active-Backup)"
    
    # Konfigurasi WiFi terlebih dahulu
    cat > "$NETPLAN_DIR/01-wifi.yaml" <<EOF
network:
  version: 2
  wifis:
    $WIFI_IFACE:
      dhcp4: no
      access-points:
        "$WIFI_SSID":
          password: "$WIFI_PASS"
EOF
    
    # Konfigurasi Bonding
    if [[ -n "$STATIC_IP" ]]; then
        # Static IP
        cat > "$NETPLAN_DIR/02-bond.yaml" <<EOF
network:
  version: 2
  bonds:
    bond0:
      addresses: [$STATIC_IP]
      gateway4: $GATEWAY_IP
      nameservers:
        addresses: [$DNS_IPS]
      interfaces: [$ETH_IFACE, $WIFI_IFACE]
      parameters:
        mode: active-backup
        primary: $ETH_IFACE
        mii-monitor-interval: 100
        up-delay: 200
        down-delay: 200
EOF
    else
        # DHCP
        cat > "$NETPLAN_DIR/02-bond.yaml" <<EOF
network:
  version: 2
  bonds:
    bond0:
      dhcp4: yes
      interfaces: [$ETH_IFACE, $WIFI_IFACE]
      parameters:
        mode: active-backup
        primary: $ETH_IFACE
        mii-monitor-interval: 100
        up-delay: 200
        down-delay: 200
EOF
    fi
    
    # Apply
    netplan generate
    netplan apply
    
    # Setup monitoring script
    setup_failover_monitor
}

setup_ethernet_only() {
    echo "    → Mode: Ethernet Only"
    
    if [[ -n "$STATIC_IP" ]]; then
        cat > "$NETPLAN_DIR/01-netcfg.yaml" <<EOF
network:
  version: 2
  ethernets:
    $ETH_IFACE:
      addresses: [$STATIC_IP]
      gateway4: $GATEWAY_IP
      nameservers:
        addresses: [$DNS_IPS]
      dhcp4: no
EOF
    else
        cat > "$NETPLAN_DIR/01-netcfg.yaml" <<EOF
network:
  version: 2
  ethernets:
    $ETH_IFACE:
      dhcp4: yes
EOF
    fi
    
    netplan generate
    netplan apply
}

setup_wifi_only() {
    echo "    → Mode: WiFi Only"
    
    if [[ -n "$STATIC_IP" ]]; then
        cat > "$NETPLAN_DIR/01-netcfg.yaml" <<EOF
network:
  version: 2
  wifis:
    $WIFI_IFACE:
      addresses: [$STATIC_IP]
      gateway4: $GATEWAY_IP
      nameservers:
        addresses: [$DNS_IPS]
      dhcp4: no
      access-points:
        "$WIFI_SSID":
          password: "$WIFI_PASS"
EOF
    else
        cat > "$NETPLAN_DIR/01-netcfg.yaml" <<EOF
network:
  version: 2
  wifis:
    $WIFI_IFACE:
      dhcp4: yes
      access-points:
        "$WIFI_SSID":
          password: "$WIFI_PASS"
EOF
    fi
    
    netplan generate
    netplan apply
}

setup_failover_monitor() {
    echo "    → Membuat monitor failover..."
    
    cat > /usr/local/bin/netfailover.sh <<'EOF'
#!/bin/bash
# Auto failover monitor script

LOG_FILE="/var/log/netfailover.log"
BOND_IFACE="bond0"
ETH_IFACE=$(cat /proc/net/bonding/bond0 2>/dev/null | grep "Slave Interface" | head -1 | awk '{print $3}')
WIFI_IFACE=$(cat /proc/net/bonding/bond0 2>/dev/null | grep "Slave Interface" | tail -1 | awk '{print $3}')

# Cek status bond
if [[ -f /proc/net/bonding/bond0 ]]; then
    ACTIVE_SLAVE=$(cat /proc/net/bonding/bond0 | grep "Currently Active Slave" | awk '{print $4}')
    PRIMARY=$(cat /proc/net/bonding/bond0 | grep "Primary Slave" | awk '{print $3}')
    
    if [[ "$ACTIVE_SLAVE" != "$PRIMARY" ]]; then
        echo "$(date): FAILOVER aktif - $ACTIVE_SLAVE digunakan (primary: $PRIMARY)" >> "$LOG_FILE"
    fi
fi

# Test connectivity
GATEWAY=$(ip route | grep default | awk '{print $3}' | head -1)
if [[ -n "$GATEWAY" ]]; then
    if ! ping -c 2 -W 3 "$GATEWAY" > /dev/null 2>&1; then
        echo "$(date): WARNING - Gateway $GATEWAY tidak merespons" >> "$LOG_FILE"
        
        # Force re-evaluate bond
        if [[ -f /sys/class/net/bond0/bonding/slaves ]]; then
            echo "-$ETH_IFACE" > /sys/class/net/bond0/bonding/slaves 2>/dev/null || true
            sleep 1
            echo "+$ETH_IFACE" > /sys/class/net/bond0/bonding/slaves 2>/dev/null || true
        fi
    fi
fi
EOF

    chmod +x /usr/local/bin/netfailover.sh
    
    # Cron job setiap 2 menit
    echo "*/2 * * * * root /usr/local/bin/netfailover.sh" > /etc/cron.d/netfailover
    
    echo "    ✓ Monitor failover aktif"
}

#-------------------------------------------------------------------------------
# FUNGSI TWEAK PERFORMANCE
#-------------------------------------------------------------------------------
setup_performance() {
    echo "[*] Optimasi performance untuk headless..."
    
    # Reduce swappiness
    sysctl vm.swappiness=10
    echo "vm.swappiness=10" >> /etc/sysctl.conf
    
    # Enable IP forwarding (untuk remote access)
    sysctl net.ipv4.ip_forward=1
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    
    # Disable IPv6 jika tidak diperlukan (opsional)
    # echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
    
    # Tweak SSH untuk koneksi lambat
    echo "UseDNS no" >> /etc/ssh/sshd_config
    echo "GSSAPIAuthentication no" >> /etc/ssh/sshd_config
    
    systemctl restart ssh
}

#-------------------------------------------------------------------------------
# FUNGSI RINGKASAN & VALIDASI
#-------------------------------------------------------------------------------
show_summary() {
    echo ""
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║           SETUP HEADLESS COMPLETE                            ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    echo "Hardware Terdeteksi:"
    echo "  • Ethernet: ${ETH_IFACE:-N/A}"
    echo "  • WiFi: ${WIFI_IFACE:-N/A}"
    echo "  • Display Manager: $DISPLAY_MGR (dinonaktifkan)"
    echo ""
    echo "Konfigurasi Aktif:"
    echo "  • Boot Target: $(systemctl get-default)"
    echo "  • SSH Port: $SSH_PORT"
    echo "  • User SSH: $ALLOWED_USER"
    echo ""
    echo "Network Setup:"
    if [[ -n "$ETH_IFACE" && -n "$WIFI_IFACE" ]]; then
        echo "  • Mode: Active-Backup Bonding (LAN primary)"
        echo "  • Interface: bond0 ($ETH_IFACE + $WIFI_IFACE)"
    elif [[ -n "$ETH_IFACE" ]]; then
        echo "  • Mode: Ethernet Only"
        echo "  • Interface: $ETH_IFACE"
    else
        echo "  • Mode: WiFi Only"
        echo "  • Interface: $WIFI_IFACE"
        echo "  • SSID: $WIFI_SSID"
    fi
    echo ""
    echo "IP Address:"
    ip addr show | grep -E "inet |bond0|eth|wlan" | head -5
    echo ""
    echo "Perintah untuk remote access:"
    echo "  ssh -X $ALLOWED_USER@$(hostname -I | awk '{print $1}')"
    echo ""
    echo "Log file: /var/log/netfailover.log"
    echo ""
    echo "REBOOT diperlukan untuk menerapkan semua perubahan!"
    echo "Jalankan: sudo reboot"
    echo ""
}

#-------------------------------------------------------------------------------
# MAIN EXECUTION
#-------------------------------------------------------------------------------
main() {
    # Cek root
    if [[ $EUID -ne 0 ]]; then
        echo "Error: Script harus dijalankan dengan sudo!"
        exit 1
    fi
    
    # Cek konfigurasi WiFi
    if [[ -n "$WIFI_IFACE" && ( -z "$WIFI_SSID" || -z "$WIFI_PASS" ) ]]; then
        echo "Error: WiFi interface terdeteksi tetapi WIFI_SSID dan WIFI_PASS belum diisi!"
        echo ""
        echo "Gunakan environment variable:"
        echo "  sudo WIFI_SSID='SSID_Anda' WIFI_PASS='Password_Anda' bash scripts/setup/ubuntu-headless.sh"
        echo ""
        echo "Atau isi langsung di bagian konfigurasi script ini."
        exit 1
    fi
    
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║   Ubuntu Headless + SSH + Auto-Failover Setup               ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    
    detect_hardware
    echo ""
    install_packages
    echo ""
    setup_headless
    echo ""
    setup_ssh
    echo ""
    setup_failover
    echo ""
    setup_performance
    echo ""
    show_summary
}

# Jalankan
main
